
import './App.css';
import FriendlyCaptcha from './FriendlyCaptcha';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <p>
          This is to test the verification of puzzle solution generated by the Widget.
          Please do not verify solutions in the browser, as it exposes your API Key.
        </p>
        <FriendlyCaptcha sitekey="<YOUR_SITEKEY>" secret="<YOUR_API_SECRET>"></FriendlyCaptcha>
      </header>
    </div>
  );
}

export default App;
