
import './App.css';
import FriendlyCaptcha from './FriendlyCaptcha';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <p>
          This is to test the verification of puzzle solution generated by the Widget.
          Please do not verify solutions in the browser, as it exposes your API Key.
        </p>
        <FriendlyCaptcha sitekey="FCMHRN176NSBB14H" secret="A1T2QIHI00HUCRDDS5A3V4EHIV4QTGM41HKKN5HAITK1L6838FE8RE2N2R"></FriendlyCaptcha>
      </header>
    </div>
  );
}

export default App;
